#! /usr/bin/env bash

# check that the oeb pin is low/high based on io_in and io_out connections

export DESIGN_NAME=$1

# Check for LVS_ROOT
if [[ -z "$LVS_ROOT" ]]; then
	echo "LVS_ROOT not set."
	exit 1
fi

echo "WORK_ROOT   : ${WORK_ROOT:=$(pwd)/$DESIGN_NAME}"
echo "LOG_ROOT    : ${LOG_ROOT:=$(pwd)/$DESIGN_NAME}"
echo "SIGNOFF_ROOT: ${SIGNOFF_ROOT:=$(pwd)/$DESIGN_NAME}"
export LOG_ROOT SIGNOFF_ROOT WORK_ROOT

mkdir -p $LOG_ROOT $SIGNOFF_ROOT $WORK_ROOT
export RESULTS_DIR=$WORK_ROOT/ext

if [[ ! -f $WORK_ROOT/cvcrc.oeb ]]; then
	if [[ ! -f $WORK_ROOT/cvcrc ]]; then
		cp $LVS_ROOT/tech/$PDK/cvcrc $WORK_ROOT/cvcrc
	fi
	sed 's/cvc.log/cvc.oeb.log/' $WORK_ROOT/cvcrc >$WORK_ROOT/cvcrc.oeb
fi

if [[ $DESIGN_NAME == user_analog_project_wrapper ]]; then
	cat >$WORK_ROOT/cvc.oeb.script <<-cvcin
		gn io_in[0]
		gn io_in[1]
		gn io_in[2]
		gn io_in[3]
		gn io_in[4]
		gn io_in[5]
		gn io_in[6]
		gn io_in[7]
		gn io_in[8]
		gn io_in[9]
		gn io_in[10]
		gn io_in[11]
		gn io_in[12]
		gn io_in[13]
		gn io_in[14]
		gn io_in[15]
		gn io_in[16]
		gn io_in[17]
		gn io_in[18]
		gn io_in[19]
		gn io_in[20]
		gn io_in[21]
		gn io_in[22]
		gn io_in[23]
		gn io_in[24]
		gn io_in[25]
		gn io_in[26]
		gn io_in[27]
		gn io_in[28]
		gn io_in[29]
		gn io_in[30]
		gn io_in[31]
		gn io_in[32]
		gn io_in[33]
		gn io_in[34]
		gn io_in[35]
		gn io_in[36]
		gn io_in[37]
		gn io_in_3v3[0]
		gn io_in_3v3[1]
		gn io_in_3v3[2]
		gn io_in_3v3[3]
		gn io_in_3v3[4]
		gn io_in_3v3[5]
		gn io_in_3v3[6]
		gn io_in_3v3[7]
		gn io_in_3v3[8]
		gn io_in_3v3[9]
		gn io_in_3v3[10]
		gn io_in_3v3[11]
		gn io_in_3v3[12]
		gn io_in_3v3[13]
		gn io_in_3v3[14]
		gn io_in_3v3[15]
		gn io_in_3v3[16]
		gn io_in_3v3[17]
		gn io_in_3v3[18]
		gn io_in_3v3[19]
		gn io_in_3v3[20]
		gn io_in_3v3[21]
		gn io_in_3v3[22]
		gn io_in_3v3[23]
		gn io_in_3v3[24]
		gn io_in_3v3[25]
		gn io_in_3v3[26]
		gn io_in_3v3[27]
		gn io_in_3v3[28]
		gn io_in_3v3[29]
		gn io_in_3v3[30]
		gn io_in_3v3[31]
		gn io_in_3v3[32]
		gn io_in_3v3[33]
		gn io_in_3v3[34]
		gn io_in_3v3[35]
		gn io_in_3v3[36]
		gn io_in_3v3[37]
		gn io_out[0]
		gn io_out[1]
		gn io_out[2]
		gn io_out[3]
		gn io_out[4]
		gn io_out[5]
		gn io_out[6]
		gn io_out[7]
		gn io_out[8]
		gn io_out[9]
		gn io_out[10]
		gn io_out[11]
		gn io_out[12]
		gn io_out[13]
		gn io_out[14]
		gn io_out[15]
		gn io_out[16]
		gn io_out[17]
		gn io_out[18]
		gn io_out[19]
		gn io_out[20]
		gn io_out[21]
		gn io_out[22]
		gn io_out[23]
		gn io_out[24]
		gn io_out[25]
		gn io_out[26]
		gn io_out[27]
		gn io_out[28]
		gn io_out[29]
		gn io_out[30]
		gn io_out[31]
		gn io_out[32]
		gn io_out[33]
		gn io_out[34]
		gn io_out[35]
		gn io_out[36]
		gn io_out[37]
		gn io_oeb[0]
		gn io_oeb[1]
		gn io_oeb[2]
		gn io_oeb[3]
		gn io_oeb[4]
		gn io_oeb[5]
		gn io_oeb[6]
		gn io_oeb[7]
		gn io_oeb[8]
		gn io_oeb[9]
		gn io_oeb[10]
		gn io_oeb[11]
		gn io_oeb[12]
		gn io_oeb[13]
		gn io_oeb[14]
		gn io_oeb[15]
		gn io_oeb[16]
		gn io_oeb[17]
		gn io_oeb[18]
		gn io_oeb[19]
		gn io_oeb[20]
		gn io_oeb[21]
		gn io_oeb[22]
		gn io_oeb[23]
		gn io_oeb[24]
		gn io_oeb[25]
		gn io_oeb[26]
		gn io_oeb[27]
		gn io_oeb[28]
		gn io_oeb[29]
		gn io_oeb[30]
		gn io_oeb[31]
		gn io_oeb[32]
		gn io_oeb[33]
		gn io_oeb[34]
		gn io_oeb[35]
		gn io_oeb[36]
		gn io_oeb[37]
		q
	cvcin
else
	cat >$WORK_ROOT/cvc.oeb.script <<-cvcin
		c 6
		gn io_in[0]
		gn io_in[1]
		gn io_in[2]
		gn io_in[3]
		gn io_in[4]
		gn io_in[5]
		gn io_in[6]
		gn io_in[7]
		gn io_in[8]
		gn io_in[9]
		gn io_in[10]
		gn io_in[11]
		gn io_in[12]
		gn io_in[13]
		gn io_in[14]
		gn io_in[15]
		gn io_in[16]
		gn io_in[17]
		gn io_in[18]
		gn io_in[19]
		gn io_in[20]
		gn io_in[21]
		gn io_in[22]
		gn io_in[23]
		gn io_in[24]
		gn io_in[25]
		gn io_in[26]
		gn io_in[27]
		gn io_in[28]
		gn io_in[29]
		gn io_in[30]
		gn io_in[31]
		gn io_in[32]
		gn io_in[33]
		gn io_in[34]
		gn io_in[35]
		gn io_in[36]
		gn io_in[37]
		gn io_out[0]
		gn io_out[1]
		gn io_out[2]
		gn io_out[3]
		gn io_out[4]
		gn io_out[5]
		gn io_out[6]
		gn io_out[7]
		gn io_out[8]
		gn io_out[9]
		gn io_out[10]
		gn io_out[11]
		gn io_out[12]
		gn io_out[13]
		gn io_out[14]
		gn io_out[15]
		gn io_out[16]
		gn io_out[17]
		gn io_out[18]
		gn io_out[19]
		gn io_out[20]
		gn io_out[21]
		gn io_out[22]
		gn io_out[23]
		gn io_out[24]
		gn io_out[25]
		gn io_out[26]
		gn io_out[27]
		gn io_out[28]
		gn io_out[29]
		gn io_out[30]
		gn io_out[31]
		gn io_out[32]
		gn io_out[33]
		gn io_out[34]
		gn io_out[35]
		gn io_out[36]
		gn io_out[37]
		gn io_oeb[0]
		gn io_oeb[1]
		gn io_oeb[2]
		gn io_oeb[3]
		gn io_oeb[4]
		gn io_oeb[5]
		gn io_oeb[6]
		gn io_oeb[7]
		gn io_oeb[8]
		gn io_oeb[9]
		gn io_oeb[10]
		gn io_oeb[11]
		gn io_oeb[12]
		gn io_oeb[13]
		gn io_oeb[14]
		gn io_oeb[15]
		gn io_oeb[16]
		gn io_oeb[17]
		gn io_oeb[18]
		gn io_oeb[19]
		gn io_oeb[20]
		gn io_oeb[21]
		gn io_oeb[22]
		gn io_oeb[23]
		gn io_oeb[24]
		gn io_oeb[25]
		gn io_oeb[26]
		gn io_oeb[27]
		gn io_oeb[28]
		gn io_oeb[29]
		gn io_oeb[30]
		gn io_oeb[31]
		gn io_oeb[32]
		gn io_oeb[33]
		gn io_oeb[34]
		gn io_oeb[35]
		gn io_oeb[36]
		gn io_oeb[37]
		q
	cvcin
fi


start_time=$SECONDS
cvc_rv -i $WORK_ROOT/cvcrc.oeb <$WORK_ROOT/cvc.oeb.script

cvc_status=$?

runtime=$((SECONDS - start_time))
hours=$((runtime / 3600))
minutes=$(((runtime % 3600) / 60))
seconds=$(((runtime % 3600) % 60))
printf "Runtime: %d:%02d:%02d (hh:mm:ss)\n" $hours $minutes $seconds >>$WORK_ROOT/cvc.log

if [[ $WORK_ROOT != $LOG_ROOT ]]; then
	cp $WORK_ROOT/cvc.log $LOG_ROOT/cvc.oeb.log
fi

awk '
	/^> gn io_in/ {
		net = gensub(/.*\[([0-9]*)\]/, "\\1", 1);
		getline;
		getline;
		in_connections[net] = $3 + $5 + $7;
	}
	/^> gn io_out/ {
		net = gensub(/.*\[([0-9]*)\]/, "\\1", 1);
		getline;
		getline;
		out_connections[net] = $3 + $5 + $7;
	}
	/^> gn io_oeb/ {
		net = gensub(/.*\[([0-9]*)\]/, "\\1", 1);
		getline;
		getline;
		oeb_connections[net] = $3 + $5 + $7;
		# 2 blank lines mark the end of a segment
		while ( NF > 0 ) {
			if ( /^Min path/ ) {
				while ( NF > 0 ) {
					min[net] = $1;
					getline;
				}
			} else if ( /^Max path/ ) {
				while ( NF > 0 ) {
					max[net] = $1;
					getline;
				}
			} else {
				while ( NF > 0 ) {
					getline;
				}
			}
			getline;
		}
	}
	END {
		for ( i in oeb_connections ) {
			if ( in_connections[i] > 0 && out_connections[i] > 0 ) {
				if ( min[i] !~ /vss/ || ! ( max[i] ~ /vdd/ || max[i] ~ /vcc/ ) ) {
					print i, "in:", in_connections[i], "out:", out_connections[i], "oeb:", min[i] "/" max[i];
				}
			} else if ( in_connections[i] > 0 ) {
				if ( ! ( max[i] ~ /vdd/ || max[i] ~ /vcc/ ) ) {
					print i, "in:", in_connections[i], "out:", out_connections[i], "oeb:", min[i] "/" max[i];
				}
			} else if ( out_connections[i] > 0 ) {
				if ( min[i] !~ /vss/ ) {
					print i, "in:", in_connections[i], "out:", out_connections[i], "oeb:", min[i] "/" max[i];
				}
			}
		}
	}' $LOG_ROOT/cvc.oeb.log > $SIGNOFF_ROOT/cvc.oeb.report

if [[ $cvc_status -eq 0 && $(grep '^CVC: End:' $LOG_ROOT/cvc.oeb.log | wc -l) -ne 1 ]]; then
	# CVC finished abnormally
	exit 3

elif [[ $cvc_status -eq 0 && $(cat $SIGNOFF_ROOT/cvc.oeb.report | wc -w) -gt 0 ]]; then
	# CVC finished normally, but detected errors
	exit 4

else
	exit $cvc_status
fi
