#! /usr/bin/env bash
#   convert_layout: Converts layout from one format to another based on file extensions

#   Copyright 2025 D. Mitch Bailey  cvc at shuharisystem dot com

#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.

# Use case
# convert_layout input_file output_file
if [[ $# -ne 2 ]]; then
	echo "usage: convert_layout input_file output_file"
	exit 1
fi

export INPUT_FILE=$1
export OUTPUT_FILE=$2

echo "INPUT_FILE   : $INPUT_FILE"
echo "OUTPUT_FILE  : $OUTPUT_FILE"

rm -f convert_layout.log

log_file=convert_layout.log

BASE_INPUT=${INPUT_FILE%.gz}
BASE_OUTPUT=${OUTPUT_FILE%.gz}

conversion="${BASE_INPUT##*.}2${BASE_OUTPUT##*.}"
if ! [[ "$conversion" =~ ^(cif|gds|oas)2(cif|gds|oas)$ ]]; then
	echo "Error: conversion $conversion not supported."
	exit 2
fi
	
echo "
Converting $INPUT_FILE to $OUTPUT_FILE"

date "+BEGIN: %c" >$log_file
start_time=$SECONDS

cat >convert_layout.$$.py <<-EOF
	import pya

	app = pya.Application.instance()
	opt = pya.SaveLayoutOptions()
	layout_view = pya.Layout()

	input_layout = "$INPUT_FILE"
	output_layout = "$OUTPUT_FILE"
	print("[INFO] Changing from " + input_layout + "\n	to " + output_layout)
	opt.set_format_from_filename(output_layout)
	opt.oasis_substitution_char=''

	# Reading the input file and writing it to the output file name
	layout_view.read(input_layout)
	layout_view.write(output_layout, opt)

	app.exit(0)
EOF

klayout -b -rm convert_layout.$$.py |
	tee -a $log_file

rm -f convert_layout.$$.py

runtime=$((SECONDS - start_time))
hours=$((runtime / 3600))
minutes=$(((runtime % 3600) / 60))
seconds=$(((runtime % 3600) % 60))
printf "Runtime: %d:%02d:%02d (hh:mm:ss)\n" $hours $minutes $seconds >>$log_file
