#! /bin/bash
#   run_hier_check: Checks layout hierarchy against verilog

#   Copyright 2022 D. Mitch Bailey  cvc at shuharisystem dot com

#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#   
#       http://www.apache.org/licenses/LICENSE-2.0
#   
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.

# Overview:
#  1. Extract verilog hierarchy, limit to TOP_CIRCUIT and child subcircuits.
#  2. Extract gds/oas hierachy, if necessary.
#  3. Compare
#  
#  Add verilog files to '$WORK_ROOT/verilog_files'

# Use case
# run_hier_check top_netlist_block netlist gds_file [primitive_prefix [gds_prefix]]
if [ $# -lt 3 -o $# -gt 5 ]; then
	echo "usage: run_hier_check top_netlist_block netlist gds_file [primitive_prefix [gds_prefix]]"
	exit
fi

export TOP_NET=$1
export NETLIST=$2
export LAYOUT=$3
PRIMITIVE_PREFIX_FILTER='-e s/\<sky130_([^/_]*_)*_//'
if [ $# -ge 4 ]; then  # only if prefix is specified
	PRIMITIVE_PREFIX_FILTER="-e s/\\<$4//g"
fi
GDS_PREFIX_FILTER='-e s/^([A-Z0-9][A-Z0-9]_)*// -e s/\/([A-Z0-9][A-Z0-9]_)*/\//'
if [ $# -eq 5 ]; then  # only if prefix is specified
	GDS_PREFIX_FILTER="-e s/^($5)*// -e s/\/($5)*/\//"
fi

: "${LOG_ROOT:=$(pwd)}"
: "${LVS_ROOT:=$(pwd)}"
: "${SIGNOFF_ROOT:=$(pwd)}"
: "${WORK_ROOT:=$(pwd)}"
export LOG_ROOT LVS_ROOT SIGNOFF_ROOT WORK_ROOT

log_file=$LOG_ROOT/$TOP_NET.hier.log

date "+BEGIN: %c" > $log_file
start_time=$SECONDS

grep -v ^# $WORK_ROOT/$TOP_NET.verilog_files | \
	sed -e 's,$::env(\([^)]*\)),$\1,' | \
	envsubst > $WORK_ROOT/$TOP_NET.verilog_files.bash

sed '/^[ 	]*module[ 	].*[^ 	](/s/(/ (/' $NETLIST `cat $WORK_ROOT/$TOP_NET.verilog_files.bash | grep -v ^#` | \
	awk -v top=$TOP_NET '
		$1 ~ /^\/\*/ {
			while ( ! /\*\// ) {
				getline;
			}
		}
		$1 == "module" {
			if ( $2 in modules ) {
				print "Duplicate module definition", $2 > "'$log_file'";
			}
			module = $2;
			next;
		}
		$1 ~ /^\/\// {
			next;
		}
		/ \(/ && ! /^[ 		]*\/\*/ {
			key = module "/" $1;
			if ( key in hier ) {
				hier[key] += 1;
			} else {
				subcells[module] = subcells[module] " " $1;
				hier[key] = 1;
			}
		}
		END {
			print_subckt[top] = 1;
			AddPrintSubckts(subcells[top]);
			for ( key in hier ) {
				split(key, path, "/");
				if ( path[1] in print_subckt ) {
					print key, hier[key];
				}
			}
		}
		function AddPrintSubckts(subckt_list, subckts, subckt_it) {
			subcell_count = split(subckt_list, subckts);
			for ( subckt_it in subckts ) {
				print_subckt[subckts[subckt_it]] = 1;
				AddPrintSubckts(subcells[subckts[subckt_it]]);
			}
		}' - | \
	grep -v // | \
	sed -E $PRIMITIVE_PREFIX_FILTER | \
	sort > $WORK_ROOT/$TOP_NET.verilog.hier

if [ ${LAYOUT##*.} == "gz" ]; then
	CAT=zcat
	BASE_LAYOUT=${LAYOUT%.gz}
else
	CAT=cat
	BASE_LAYOUT=$LAYOUT
fi
EXT=${BASE_LAYOUT##*.}
if [ "$EXT" == "txt" ]; then
	TEXT_FILE=$BASE_LAYOUT	
elif [ "$EXT" == "gds" -o "$EXT" == "oas" ]; then
	TEXT_FILE=$WORK_ROOT/gds_text/$TOP_NET.gds.txt
	mkdir -p $WORK_ROOT/gds_text
	echo "Creating $TEXT_FILE.gz from $LAYOUT..." | \
		tee -a $log_file
cat > $WORK_ROOT/gds2txt.py <<-EOF
	import pya
	
	app = pya.Application.instance()
	opt = pya.SaveLayoutOptions()
	view = pya.Layout()
	
	input_layout = "$LAYOUT"
	output = "$TEXT_FILE"
	# Setting the name of the output file and setting the substitution character
	print("[INFO] Changing from " + input_layout + " to " + output)
	opt.set_format_from_filename(output)
	opt.oasis_substitution_char=''
	
	# Reading the input file and writing it to the output file name
	view.read(input_layout)
	view.write(output, opt)
	
	app.exit(0)
EOF
	klayout -b -rm $WORK_ROOT/gds2txt.py | \
		tee -a $log_file
	gzip -f $TEXT_FILE
	CAT=zcat
fi

$CAT $TEXT_FILE | \
awk '
	/^STRNAME/ {
		module = $2;
	}
	/^SNAME/ {
		key = module "/" $2;
		if ( key in hier ) {
			hier[key] += 1;
		} else {
			hier[key] = 1;
		}
	}
	END {
		for ( key in hier ) {
			print key, hier[key];
		}
	}' - | \
	sed -E $GDS_PREFIX_FILTER $PRIMITIVE_PREFIX_FILTER | \
	sort -u > $WORK_ROOT/$TOP_NET.layout.hier

comm -23 $WORK_ROOT/$TOP_NET.verilog.hier $WORK_ROOT/$TOP_NET.layout.hier | \
	awk '{print $1}' | \
	fgrep -f - $WORK_ROOT/$TOP_NET.verilog.hier $WORK_ROOT/$TOP_NET.layout.hier | \
	sed 's/:/ /' | \
	awk '	BEGIN {
			print "verilog,,layout";
		}
		/verilog.hier/ {
			verilog_count += 1;
			verilog[verilog_count] = $2;
			instances[$2] = $3;
		}
		/layout.hier/ {
			if ( match_count == verilog_count || verilog[match_count+1] > $2 ) {
				print ",," $2 "," $3;
			} else {
				while ( match_count < verilog_count && verilog[match_count+1] <= $2 ) {
					match_count += 1;
					if ( verilog[match_count] < $2 ) {
						print verilog[match_count] "," instances[verilog[match_count]];
					} else {  # equal
						print verilog[match_count] "," instances[verilog[match_count]] "," $2 "," $3;
					}
				}
				if ( match_count == verilog_count && verilog[match_count] != $2 ) {
					print verilog[match_count] "," instances[verilog[match_count]];
				}
			}
		}
		END {
			while ( match_count < verilog_count ) {
				match_count += 1;
				print verilog[match_count] "," instances[verilog[match_count]];
			}
		}' - > $SIGNOFF_ROOT/$TOP_NET.hier.csv

if [[ $(cat $SIGNOFF_ROOT/$TOP_NET.hier.csv | wc -l) -eq 1 ]]; then
	echo "Hierarchy check for $TOP_NET passed." | \
		tee -a $log_file
else
	echo "Hierarchy check for $TOP_NET failed. See $SIGNOFF_ROOT/$TOP_NET.hier.csv" | \
		tee -a $log_file
fi

date "+END: %c" >> $log_file
runtime=$(( SECONDS - start_time ))
hours=$((runtime / 3600))
minutes=$(( (runtime % 3600) / 60 ))
seconds=$(( (runtime % 3600) % 60 ))
printf "Runtime: %d:%02d:%02d (hh:mm:ss)\n" $hours $minutes $seconds >> $log_file
