#! /bin/bash
#   run_scheck: Detect well only connections in GDS file. Also run CVC for user_*project_wrapper.

#   Copyright 2022 D. Mitch Bailey  cvc at shuharisystem dot com

#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#   
#       http://www.apache.org/licenses/LICENSE-2.0
#   
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.

# Overview:
#  1. Extract gds_file with well connectivity.
#  2. Remove well connections and disconnected nets.
#  3. Extract gds_file without well connectivity.
#  4. Remove disconnected nets.
#  5. Compare
#  
#  Add cells to be flattened before extract to 'flatglob' file
#  Add cells to be extracted as black-boxes to 'abstract' file
#  Add cells to be flattened during compare to 'flatten' file
#  Add cells not to be flattened during compare to 'noflatten' file

# Use cases
# run_scheck top_block gds_file	: extract and then compare
# run_scheck top_block		: use previous extraction results to compare
if [ $# -lt 1 -o $# -gt 2 ]; then
	echo "usage: run_scheck top_block [gds_file]"
	exit
fi

export TOP=$1

# Add any cells that should be flattened before extraction to 'flatten'. globbing allowed.
export FLATGLOB_CELLS="`cat flatglob 2>/dev/null | grep -v '^#'`"
# Add any empty cells that should be extracted as black-boxes to 'abstract'.
export ABSTRACT_CELLS="`cat abstract 2>/dev/null | grep -v '^#'`"

# Verify that magic and netgen are executable.
which magic >& /dev/null
if [[ $? != 0 ]]; then
	echo "Error: Could not execute magic."
	exit 1
fi
which netgen >& /dev/null
if [[ $? != 0 ]]; then
	echo "Error: Could not execute netgen."
	exit 1
fi

#  Create extraction result directories. No error if they already exist.
mkdir -p $TOP.ext $TOP.nowell.ext

if [ $# == 1 ]; then
	# No gds_file so LVS only. Check for existing extraction results.
	if [ ! -f $TOP.ext/$TOP.gds.nowell.spice ]; then
		echo "Error: missing $TOP.ext/$TOP.gds.nowell.spice"
		echo "Specify gds_file to create"
		echo "usage: run_scheck top_block [gds_file]"
		exit
	fi
	if [ ! -f $TOP.nowell.ext/$TOP.gds.nowell.spice ]; then
		echo "Error: missing $TOP.nowell.ext/$TOP.gds.nowell.spice"
		echo "Specify gds_file to create"
		echo "usage: run_scheck top_block [gds_file]"
		exit
	fi
else
	# Specified gds_file, so extract it.
	export CURRENT_GDS=$2

	if [ ! -f $CURRENT_GDS ]; then
		echo "Error: File not found: $CURRENT_GDS"
		exit 2
	fi

	# Remove any previous extraction results
	rm -rf {$TOP.ext,$TOP.nowell.ext}/*.ext

	export RUN_DIR=$TOP.ext
	echo "Extracting layout with well in background process. See $TOP.ext.log."
	#  1. Extract gds_file with well connectivity
	( date "+BEGIN: %c" > $TOP.ext.log; \
	start_time=$SECONDS; \
	magic -dnull -noc -rcfile tech/magicrc.sky130B scripts/gds.spice.tcl < /dev/null >> $TOP.ext.log 2>&1; \
	#  2. Remove well connections and disconnected nets.; \
	sed -f scripts/remove_well.sed $TOP.ext/$TOP.gds.spice | \
		awk -f scripts/remove_disconnect.awk - > $TOP.ext/$TOP.gds.nowell.spice; \
	date "+END: %c" >> $TOP.ext.log; \
	runtime=$(( SECONDS - start_time )); \
	hours=$((runtime / 3600)); \
	minutes=$(( (runtime % 3600) / 60 )); \
	seconds=$(( (runtime % 3600) % 60 )); \
	awk "END {printf \"Runtime: %d:%02d:%02d (hh:mm:ss)\n\", $hours, $minutes, $seconds}" /dev/null >> $TOP.ext.log ) &

	export RUN_DIR=$TOP.nowell.ext
	echo "Extracting layout without well in background process. See $TOP.nowell.ext.log."
	#  3. Extract gds_file without well connectivity
	( date "+BEGIN: %c" > $TOP.nowell.ext.log; \
	start_time=$SECONDS; \
	magic -dnull -noc -rcfile tech/magicrc.sky130B.nowell scripts/gds.spice.tcl < /dev/null > $TOP.nowell.ext.log 2>&1; \
	#  4. Remove disconnected nets.; \
	awk -f scripts/remove_disconnect.awk $TOP.nowell.ext/$TOP.gds.spice > $TOP.nowell.ext/$TOP.gds.nowell.spice; \
	date "+END: %c" >> $TOP.nowell.ext.log; \
	runtime=$(( SECONDS - start_time )); \
	hours=$((runtime / 3600)); \
	minutes=$(( (runtime % 3600) / 60 )); \
	seconds=$(( (runtime % 3600) % 60 )); \
	awk "END {printf \"Runtime: %d:%02d:%02d (hh:mm:ss)\n\", $hours, $minutes, $seconds}" /dev/null >> $TOP.nowell.ext.log ) &

	wait
fi

#  5. Compare
date "+BEGIN: %c" > $TOP.soft.log
start_time=$SECONDS
netgen -batch source tech/setup_file.soft.lvs | tee -a $TOP.soft.log 2>&1
date "+END: %c" >> $TOP.soft.log
runtime=$(( SECONDS - start_time ))
hours=$((runtime / 3600))
minutes=$(( (runtime % 3600) / 60 ))
seconds=$(( (runtime % 3600) % 60 ))
awk "END {printf \"Runtime: %d:%02d:%02d (hh:mm:ss)\n\", $hours, $minutes, $seconds}" /dev/null >> $TOP.soft.log
