#! /bin/bash

export DESIGN_NAME=$1
export RESULTS_DIR=well

if [[ ! -f $RESULTS_DIR/$DESIGN_NAME.cdl ]] ; then
	./spi2cdl $RESULTS_DIR/$DESIGN_NAME.gds.spice > $RESULTS_DIR/$DESIGN_NAME.cdl
fi

cvc cvcrc.sky130A
