#! /bin/bash
#   run_full_lvs: extract (if necessary) and run lvs with netgen 

#   Copyright 2022 D. Mitch Bailey  cvc at shuharisystem dot com

#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#   
#       http://www.apache.org/licenses/LICENSE-2.0
#   
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.

# Overview:
#  1. Extract gds_file (if given)
#  2. Remove well connections and disconnected nets.
#  3. Extract gds_file without well connectivity.
#  4. Remove disconnected nets.
#  
#  Add verilog files to 'verilog_files'
#  Add spice files to 'spice_files'
#  Add cells to be flattened before extract to 'flatten' file
#  Add cells not to be flattened during compare to 'noflatten' file

# Use cases
# run_full_lvs top_netlist_block netlist top_layout_block gds_file : extract and then compare
# run_full_lvs top_netlist_block netlist top_layout_block	   : compare
if [[ -z "${LOG_ROOT}" ]]; then
    LOG_ROOT=$(pwd)
fi

if [[ -z "${SIGNOFF_ROOT}" ]]; then
    SIGNOFF_ROOT=$(pwd)
fi

if [[ -z "${LVS_ROOT}" ]]; then
    LVS_ROOT=$(pwd)
fi

if [ $# -lt 1 -o $# -gt 4 ]; then
	echo "usage: run_full_lvs top_netlist_block [netlist [top_layout_block [gds_file]]]"
	exit
fi

export TOP_NET=$1
if [ $# -ge 2 ]; then
	export NETLIST=$2
else
	export NETLIST=../verilog/gl/$TOP_NET.v
fi
if [ $# -ge 3 ]; then
	export TOP_LAYOUT=$3
else
	export TOP_LAYOUT=$TOP_NET
fi

# Add any cells that should be flattened before extraction to 'flatten'. globbing allowed.
export FLATGLOB_CELLS="`cat $LVS_ROOT/flatglob 2>/dev/null | grep -v '^#'`"
# Add any empty cells that should be extracted as black-boxes to 'abstract'.
export ABSTRACT_CELLS="`cat $LVS_ROOT/abstract 2>/dev/null | grep -v '^#'`"

# Verify that magic and netgen are executable.
if [ $# == 4 ]; then  # only if gds is specified
	which magic >& /dev/null
	if [[ $? != 0 ]]; then
		echo "Error: Could not execute magic."
		exit 1
	fi
fi
which netgen >& /dev/null
if [[ $? != 0 ]]; then
	echo "Error: Could not execute netgen."
	exit 1
fi

#  Create extraction result directories. No error if they already exist.
EXT_DIR=$LVS_ROOT/$TOP_LAYOUT.ext
mkdir -p $EXT_DIR

if [ $# -lt 4 ]; then
	# No gds_file so LVS only. Check for existing extraction results.
	if [ ! -f $EXT_DIR/$TOP_LAYOUT.gds.spice ]; then
		echo "Error: missing $EXT_DIR/$TOP_LAYOUT.gds.spice"
		echo "Specify gds_file to create"
		echo "usage: run_full_lvs top_netlist_block netlist top_layout_block [gds_file]"
		exit
	fi
else
	# Specified gds_file, so extract it.
	export CURRENT_GDS=$4

	if [ ! -f $CURRENT_GDS ]; then
		echo "Error: File not found: $CURRENT_GDS"
		exit 2
	fi

	# Remove any previous extraction results
	rm -rf $EXT_DIR/*.ext{,.gz}

	#  1. Extract gds_file 
	#  Note: uses the same extraction commands as sconnect, so symbolic links to the EXT_DIR may be used
	date "+BEGIN: %c" > $LOG_ROOT/$TOP_LAYOUT.ext.log
	start_time=$SECONDS

	if [ ${NETLIST##*.} == "spice" ]; then
		echo "Extracting as analog. Top ports connected by name."
		EXT_TYPE=analog
	else
		echo "Extracting as digital. Top ports unique."
		EXT_TYPE=digital
	fi

	env TOP=$TOP_LAYOUT RUN_DIR=$EXT_DIR magic -dnull -noc -rcfile $PDK_ROOT/$PDK/libs.tech/magic/$PDK.magicrc $LVS_ROOT/scripts/gds.$EXT_TYPE.spice.tcl < /dev/null | \
		tee -a $LOG_ROOT/$TOP_LAYOUT.ext.log 2>&1

	date "+END: %c" >> $LOG_ROOT/$TOP_LAYOUT.ext.log
	runtime=$(( SECONDS - start_time ))
	hours=$((runtime / 3600))
	minutes=$(( (runtime % 3600) / 60 ))
	seconds=$(( (runtime % 3600) % 60 ))
	awk "END {printf \"Runtime: %d:%02d:%02d (hh:mm:ss)\n\", $hours, $minutes, $seconds}" /dev/null >> $LOG_ROOT/$TOP_LAYOUT.ext.log

	# Compress large ext files
	gzip `find . -name '*.ext' -size +1M`
fi

#  5. Compare
if [ ! -f verilog_files ]; then
	touch verilog_files
fi

cp $LVS_ROOT/tech/sky130B_setup.tcl $LVS_ROOT/$TOP_NET.sky130B_setup.tcl
awk '
FILENAME == "flatten" && ! /^#/ {
	print "puts stdout \"Flattening", $1 "\"";
	print "flatten class {-circuit1", $1, "}";
	print "flatten class {-circuit2", $1, "}";
}' $LVS_ROOT/flatte[n] /dev/null >> $LVS_ROOT/$TOP_NET.sky130B_setup.tcl

awk '
FILENAME == "spice_files" && $1 !~ /^#/ {
	print "puts \"Reading spice netlist file", $1 "\"";
	print "readnet spice", $1, 1;
}
FILENAME == "verilog_files" && $1 !~ /^#/ {
	print "puts \"Reading verilog netlist file", $1 "\"";
	print "readnet verilog", $1, 1;
}
END {
	print "lvs {'$EXT_DIR/$TOP_LAYOUT.gds.spice' '$TOP_LAYOUT'} {'$NETLIST' '$TOP_NET'} '$LVS_ROOT/$TOP_NET'.sky130B_setup.tcl '$SIGNOFF_ROOT/$TOP_NET'.lvs.report -blackbox -json -noflatten=noflatten"
}' $LVS_ROOT/spice_file[s] $LVS_ROOT/verilog_file[s] $LVS_ROOT/flatte[n] /dev/null > $LVS_ROOT/setup_file_$TOP_NET.lvs

date "+BEGIN: %c" > $LOG_ROOT/$TOP_NET.lvs.log
start_time=$SECONDS

netgen -batch source $LVS_ROOT/setup_file_$TOP_NET.lvs | \
	tee -a $LOG_ROOT/$TOP_NET.lvs.log 2>&1

awk '
/Circuit 1 .* will not flatten/ {print $4, "is a black box in the layout"}
/Circuit 2 .* will not flatten/ {print $4, "is a black box in the netlist"}
' $SIGNOFF_ROOT/$TOP_NET.lvs.report > $LVS_ROOT/$TOP_NET.unflattened
awk '
/__fill/ {next}
/__tapvpwrvgnd/ {next}
/__fakediode/ {next}
/sky130_fd_pr__/ {next}
/Matching pins/ {print $4, "is a black box in the layout and netlist"}
' $LOG_ROOT/$TOP_NET.lvs.log >> $LVS_ROOT/$TOP_NET.unflattened
if [ -s $LVS_ROOT/$TOP_NET.unflattened ]; then
	echo "Warning: device level LVS may be incomplete due to $(cat $TOP_NET.unflattened | wc -l) unflattened cell(s): see $TOP_NET.unflattened" | \
		tee -a $SIGNOFF_ROOT/$TOP_NET.lvs.report | \
		tee -a $LOG_ROOT/$TOP_NET.lvs.log
fi

date "+END: %c" >> $LOG_ROOT/$TOP_NET.lvs.log
runtime=$(( SECONDS - start_time ))
hours=$((runtime / 3600))
minutes=$(( (runtime % 3600) / 60 ))
seconds=$(( (runtime % 3600) % 60 ))
awk "END {printf \"Runtime: %d:%02d:%02d (hh:mm:ss)\n\", $hours, $minutes, $seconds}" /dev/null >> $LOG_ROOT/$TOP_NET.lvs.log
