#! /bin/bash

export DESIGN_NAME=$1
export RESULTS_DIR=$DESIGN_NAME.ext

if [[ ! -f $RESULTS_DIR/$DESIGN_NAME.cdl ]] ; then
	echo "Creating $RESULTS_DIR/$DESIGN_NAME.cdl"
	./spi2cdl $RESULTS_DIR/$DESIGN_NAME.gds.spice > $RESULTS_DIR/$DESIGN_NAME.cdl
fi

cvc cvc/cvcrc.sky130B
