#! /bin/bash

export DESIGN_NAME=$1
export RESULTS_DIR=well

if [[ ! -f $RESULTS_DIR/$TOP_LAYOUT.cdl ]] ; then
	./spi2cdl $RESULTS_DIR/$TOP_LAYOUT.gds.spice > $RESULTS_DIR/$TOP_LAYOUT.cdl
fi

cvc cvcrc.sky130A
