#! /bin/bash

awk '
/^X.*__diode.*=/ {
        print "D" $0;
        next;
}
/^X.*__special_[^ _]*fet.*=/ || /^X.*__.fet.*=/ || /^X.*__esd_.fet.*=/ {
        print "M" $0;
        next;
}
/^X.*__pnp_.*=/ {
        print "Q" $0;
        next;
}
/^X.*__cap_mim_.*=/ {
        print "C" $0;
        next;
}
/^X.*__cap_var.*=/ {
	bulk = $4;
	$4 = "";
        print "C" $0, "$SUB=" bulk;
        next;
}
/^X.*__res_.*=/ {
	bulk = $4;
	$4 = "";
        print "R" $0, "$SUB=" bulk;
        next;
}
 {
        print $0;
}' $1

