#! /bin/bash

awk '
/^X.*pr__diode.*=/ {
        print "D" $0;
        next;
}
/^X.*pr__special_[^ _]*fet.*=/ || /^X.*pr__.fet.*=/ || /^X.*pr__esd_.fet.*=/ {
        print "M" $0;
        next;
}
/^X.*pr__pnp_.*=/ {
        print "Q" $0;
        next;
}
/^X.*pr__cap_mim_.*=/ {
        print "C" $0;
        next;
}
/^X.*pr__cap_var.*=/ {
	bulk = $4;
	$4 = "";
        print "C" $0, "$SUB=" bulk;
        next;
}
/^X.*pr__res_.*=/ {
	bulk = $4;
	$4 = "";
        print "R" $0, "$SUB=" bulk;
        next;
}
 {
        print $0;
}' $1

