#! /bin/bash

awk '
/^X.*pr__diode.*=/ || /^X.* diode_.*=/ {
        print "D" $0;
        next;
}
/^X.*pr__special_[^ _]*fet.*=/ || /^X.*pr__.fet.*=/ || /^X.*pr__esd_.fet.*=/ || /^X.*[np]fet_[0-9]*v[0-9].*=/ || /^X.*[np]mos_[36]p[03]/ {
        print "M" $0;
        next;
}
/^X.*pr__pnp_.*=/ || /^X.* pnp_.*/ {
        print "Q" $0;
        next;
}
/^X.*pr__cap_mim_.*=/ || /^X.*mim_2p0fF.*=/ || /^X.*cap_mim_2f0_m4m5/ || /^X.*cap_nmos/ {
        print "C" $0;
        next;
}
/^X.*pr__cap_var.*=/ {
	bulk = $4;
	$4 = "";
        print "C" $0, "$SUB=" bulk;
        next;
}
/^X.*pr__res_.*=/ || /^X.*ppolyf_/ {
	bulk = $4;
	$4 = "";
        print "R" $0, "$SUB=" bulk;
        next;
}
/^X.* efuse *$/ {
        print "R" $0;
        next;
}
/^R/ && NF == 4 && $4 == "0.000000" {
	$4 = "short " $4;
}
 {
        print $0;
}' $1

